repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-json
        exclude: ^(level_app/tests/mock_data/)
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        language: python
        args: ["--profile", "black"]


  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest stable version of Black
    hooks:
      - id: black
        language_version: python3
